### ISSUE TITLE
can not run tkdesigner

### ISSUE THREAD

**Issue by laoshaw** [ParthJadhav/Tkinter-Designer#135]
I did tkdesigner fileurl token and I got this:

```
Traceback (most recent call last):
  File "/home/pytest/.local/bin/tkdesigner", line 8, in <module>
    sys.exit(main())
  File "/home/pytest/.local/lib/python3.8/site-packages/tkdesigner/cli.py", line 71, in main
    designer.design()
  File "/home/pytest/.local/lib/python3.8/site-packages/tkdesigner/designer.py", line 29, in design
    code = self.to_code()
  File "/home/pytest/.local/lib/python3.8/site-packages/tkdesigner/designer.py", line 23, in to_code
    frame = Frame(window_data, self.figma_file, self.output_path)
  File "/home/pytest/.local/lib/python3.8/site-packages/tkdesigner/figma/frame.py", line 29, in __init__
    self.elements = [
TypeError: 'NoneType' object is not iterable
```

I can open url on incognito mode so the file path is correct, also I copy&paste my token.

**Comment by ParthJadhav** [comment]
You must have named some elements incorrectly... Can you share the link to your Figma File or share a screenshot of the layers panel?

**Comment by laoshaw** [comment]
tkdesigner https://www.figma.com/file/EfUAeO2K0CNKVy66c2Pm9Z/Untitled?node-id=0%3A1  your-token

the design is just a blank page with a rectangle box, the simplest design to see if tkdesigner works for me.

tried with python 3.8 and 3.9 inside/outside virtualenv,same error.

**Comment by ParthJadhav** [comment]
Tkdesigner looks for a main parent component which rectangle cant be.

Just and a Frame around the rectangle this will fix the error. But even after that the design would not work and it will have a black rectangle as you've named the rectangle element incorrectly.

Rename the "Rectangle 1" to "Rectangle".

Tkdesigner uses the names given to the elements to identify the type of element. Check the naming guide.

**Comment by laoshaw** [comment]
Works now. Thanks!!
