### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u24b8' in position 1067: character maps to <undefined>

### ISSUE THREAD

**Issue by Rehi146** [ParthJadhav/Tkinter-Designer#136]
First of all, I'd like to say that Tkinter-Designer is an amazing idea, and I sure hope to see the final output.
When running the designer, I get the next error message:
`UnicodeEncodeError: 'charmap' codec can't encode character '\u24b8' in position 1067: character maps to <undefined>`

Full output:

```
Creating Element { name: Rectangle, type: RECTANGLE }
Creating Element { name: Image, type: RECTANGLE }
Creating Element { name: Version 1.1, type: TEXT }
Creating Element { name: Button, type: GROUP }
Creating Element { name: Listening for incoming connections..., type: TEXT }
Creating Element { name: Image, type: RECTANGLE }
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\user\OneDrive\Desktop\App\Tkinter-Designer\gui\gui.py", line 72, in btn_clicked
    designer.design()
  File "C:\Users\user\OneDrive\Desktop\App\Tkinter-Designer\tkdesigner\designer.py", line 30, in design
    self.output_path.joinpath(CODE_FILE_NAME).write_text(code)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 1275, in write_text
    return f.write(data)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u24b8' in position 1067: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\App\Tkinter-Designer\gui\gui.py", line 196, in <module>   
    window.mainloop()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1429, in mainloop
    self.tk.mainloop(n)
```

This is the design:
![image](https://user-images.githubusercontent.com/42693960/133004610-b596474d-af97-49ac-abc6-492c6621b609.png)
It includes a Google Web font and gradient coloring (which I am not sure are supported on Tkinter?).

Any idea about why is this happening?

**Comment by Rehi146** [comment]
My bad, I was using the "Ⓒ", which caused some encoding problems. I omitted it and added it manually.
