### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by caobaichuan1122** [ParthJadhav/Tkinter-Designer#137]
Traceback (most recent call last):
  File "E:\Pth\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "E:\Tkinter-Designer\gui\gui.py", line 72, in btn_clicked
    designer.design()
  File "E:\Tkinter-Designer\tkdesigner\designer.py", line 29, in design
    code = self.to_code()
  File "E:\Tkinter-Designer\tkdesigner\designer.py", line 23, in to_code
    frame = Frame(window_data, self.figma_file, self.output_path)
  File "E:\Tkinter-Designer\tkdesigner\figma\frame.py", line 29, in __init__
    self.elements = [
TypeError: 'NoneType' object is not iterable

**Comment by jvendegna** [comment]
You need to make it easy for us to help you. If you have a question ask it. Consider how you ran into this error, then tell us about it. No one is going to pry information out of you to help you solve your problem. Help me help you.

**Comment by ParthJadhav** [comment]
Closing due to inactivity.
