### ISSUE TITLE
KeyError: 'document'

### ISSUE THREAD

**Issue by MyGuyCai** [ParthJadhav/Tkinter-Designer#203]
Hi,
I've been teaching my self coding and have most of the logic for my program done but now I need to work on UI.

Moving on, here are the steps I've done to try and get tkdesigner to work:
installed python3.9
added python to path
>pip install tkdesigner
>tkdesigner $FILE_URL $FIGMA_TOKEN

here is my file url: 
https://www.figma.com/file/W3ekOTW6bFvGiUrndEpC4S/Untitled?node-id=4%3A41

The callback I get is:
Traceback (most recent call last):
  File "C:\Users\Cai\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Cai\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Cai\AppData\Local\Programs\Python\Python39\Scripts\tkdesigner.exe\__main__.py", line 7, in <module>
  File "C:\Users\Cai\AppData\Local\Programs\Python\Python39\lib\site-packages\tkdesigner\cli.py", line 71, in main
    designer.design()
  File "C:\Users\Cai\AppData\Local\Programs\Python\Python39\lib\site-packages\tkdesigner\designer.py", line 29, in design
    code = self.to_code()
  File "C:\Users\Cai\AppData\Local\Programs\Python\Python39\lib\site-packages\tkdesigner\designer.py", line 21, in to_code
    window_data = self.file_data["document"]["children"][0]["children"][0]
KeyError: 'document'

Any ideas what I've missed?

**Comment by MyGuyCai** [comment]
After reading through other issues trying to find one similar I tried running tkdesigner through the GUI which has worked, guessing there is an issue with CLI or maybe I was doing something wrong.
Either way got it to work!

**Comment by jiuerbujie** [comment]
the same error, even failed using GUI

**Comment by aditdesai** [comment]
Did anyone find a solution?

**Comment by AbdulkadirH5253** [comment]
hey @aditdesai @MyGuyCai @jiuerbujie 

i see you have python installed but your running in it wrong directory mate.

open a fresh terminal or cmd and run these commands in order:

git clone https://github.com/ParthJadhav/Tkinter-Designer.git
cd tkinter-designer
pip3 install -r requirements.txt
pip3 install tkdesigner
cd tkinter-designer (optional: only if u arent still in tkinter-designer directory after the pip3 steps)
cd gui
python3 gui.py

**Comment by MyGuyCai** [comment]
@AbdulkadirH5253 
Can confirm this works, running the UI with pip gui.py allows me to get my designs

**Comment by Esavwede** [comment]
I found a Solution:
The cause of the error for me was an expired Figma Token

This is the error I got the error: 
" tkinter KeyError: 'document' "

self.file_data.['document'] was undefined  because self.file_data was equal to an error object 

![Screenshot 2024-01-17 213106](https://github.com/ParthJadhav/Tkinter-Designer/assets/56054413/d917b985-0317-4c21-bb3f-9c867e3a845b)

To Fix the error, create a new Figma Token

**Comment by phre3d** [comment]
> I found a Solution: The cause of the error for me was an expired Figma Token
...
> To Fix the error, create a new Figma Token

This essentially worked for me too. There was a typo in the Figma key and once corrected it worked fine
