### ISSUE TITLE
KeyError: 'document'

### ISSUE THREAD

**Issue by aditdesai** [ParthJadhav/Tkinter-Designer#208]
Traceback (most recent call last):
  File "c:\users\adit\appdata\local\programs\python\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\adit\appdata\local\programs\python\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Adit\AppData\Local\Programs\Python\Python38-32\Scripts\tkdesigner.exe\__main__.py", line 7, in <module>
  File "c:\users\adit\appdata\local\programs\python\python38-32\lib\site-packages\tkdesigner\cli.py", line 71, in main
    designer.design()
  File "c:\users\adit\appdata\local\programs\python\python38-32\lib\site-packages\tkdesigner\designer.py", line 29, in design
    code = self.to_code()
  File "c:\users\adit\appdata\local\programs\python\python38-32\lib\site-packages\tkdesigner\designer.py", line 21, in to_code
    window_data = self.file_data["document"]["children"][0]["children"][0]
KeyError: 'document'

This is the error I get when I run tkdesigner FILE_ID TOKEN

- Python is added to PATH
- pip install tkdesigner has already been run
- pip is up to date
- I have followed naming conventions (as far as I know)

File URL: https://www.figma.com/file/1Dd7aygqhMcCRYwtinm6Oi/File-Converter?node-id=2%3A2

![image](https://user-images.githubusercontent.com/62762086/161388163-4c86bbea-0ae3-4abc-9366-b61fcb1480ca.png)

**Comment by AbdulkadirH5253** [comment]
hey @aditdesai 

i see you have python installed but your running in it wrong directory mate.

open a fresh terminal or cmd and run these commands in order:

git clone https://github.com/ParthJadhav/Tkinter-Designer.git
cd tkinter-designer
pip3 install -r requirements.txt
pip3 install tkdesigner
cd tkinter-designer (optional: only if u arent still in tkinter-designer directory after the pip3 steps)
cd gui
python3 gui.py

**Comment by ParthJadhav** [comment]
@aditdesai did @AbdulkadirH5253 's comment help you? If yes, then you can close this issue.

**Comment by pshiri** [comment]
Hey, I am seeing this issue as well

**Comment by allanjonis** [comment]
Same error here.

**Comment by sam31046** [comment]
Hi, 
I've followed those steps which @AbdulkadirH5253 mentioned above.
But this error occurs when I run gui.py, not sure why:
**window_data = self.file_data["document"]["children"][0]["children"][0]
KeyError: 'document'**

**Comment by abdulkadirhuzeifa** [comment]
you did it?

**Comment by G4brielTerto** [comment]
I had the same error and my solution was just enable this option on creating the token

![Image](https://github.com/user-attachments/assets/a3f81dfc-d8c0-4266-ba72-b2f99315eda5)
