### ISSUE TITLE
KeyError: 'document'

### ISSUE THREAD

**Issue by StonePig** [ParthJadhav/Tkinter-Designer#250]
E:\git\Tkinter-Designer\gui>python gui.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\yaozhong\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "E:\git\Tkinter-Designer\gui\gui.py", line 72, in btn_clicked
    designer.design()
  File "E:\git\Tkinter-Designer\tkdesigner\designer.py", line 29, in design
    code = self.to_code()
  File "E:\git\Tkinter-Designer\tkdesigner\designer.py", line 21, in to_code
    window_data = self.file_data["document"]["children"][0]["children"][0]
KeyError: 'document'

**Comment by ParthJadhav** [comment]
Check this out @StonePig 

https://youtu.be/Qd-jJjduWeQ
