### ISSUE TITLE
zsh: no matches found: "my file url"

### ISSUE THREAD

**Issue by MarkLHH** [ParthJadhav/Tkinter-Designer#252]
<img width="491" alt="image" src="https://user-images.githubusercontent.com/25732653/185576363-4f266243-fb71-4767-8eb2-ae28bf68181c.png">

Hi, I am trying out the tkinter-designer. I have created a simple figma design file and when I try to generate the gui.py, I have encountered this problem.

The following is the structure of my figma design file.
<img width="748" alt="image" src="https://user-images.githubusercontent.com/25732653/185577028-4155f433-6eff-403e-849e-aab19856194b.png">

**Comment by boludoz** [comment]
same problem

`C:\Users\PC\GUI_\Tkinter-Designer>python -m tkdesigner.cli "https://www.figma.com/file/KtjrkslOvq1XSbEZDEKbV8" figd_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Directory `C:\Users\PC\GUI_\Tkinter-Designer\build` already exists.
Do you want to continue and overwrite? [N/y] y
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\PC\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\PC\GUI_\Tkinter-Designer\tkdesigner\cli.py", line 76, in <module>
    main()
  File "C:\Users\PC\GUI_\Tkinter-Designer\tkdesigner\cli.py", line 71, in main
    designer.design()
  File "C:\Users\PC\GUI_\Tkinter-Designer\tkdesigner\designer.py", line 29, in design
    code = self.to_code()
  File "C:\Users\PC\GUI_\Tkinter-Designer\tkdesigner\designer.py", line 23, in to_code
    frame = Frame(window_data, self.figma_file, self.output_path)
  File "C:\Users\PC\GUI_\Tkinter-Designer\tkdesigner\figma\frame.py", line 29, in __init__
    self.elements = [
TypeError: 'NoneType' object is not iterable`

**Comment by ParthJadhav** [comment]
Hey @MarkLHH , It seems like u missed `.cli` while executing the module.

`python3 -m tkdesigner.cli `

**Comment by LucaJaich** [comment]
I'm having the same issue and that solution didn't work
