### ISSUE TITLE
Report bug :_tkinter.TclError: couldn't recognize data in image file

### ISSUE THREAD

**Issue by qyzxg** [ParthJadhav/Tkinter-Designer#253]
- Briefly describe the bug
 when I execute gui.py, I got  _tkinter.TclError: couldn't recognize data in image file "/Users/Zhou/Project/Tkinter-Designer/gui/assets/TextBox_Bg.png"
- Operating System
    mscos, python 3.10.6 
- Please provide step by step instructions on how to reproduce the bug  
  ```python
  Traceback (most recent call last):
    File "/Users/Zhou/Project/Tkinter-Designer/gui/gui.py", line 118, in <module>
      text_box_bg = tk.PhotoImage(file=ASSETS_PATH / "TextBox_Bg.png")
    File "/Users/Zhou/.pyenv/versions/3.10.6/lib/python3.10/tkinter/__init__.py", line 4093, in __init__
      Image.__init__(self, 'photo', name, cnf, master, **kw)
    File "/Users/Zhou/.pyenv/versions/3.10.6/lib/python3.10/tkinter/__init__.py", line 4038, in __init__
      self.tk.call(('image', 'create', imgtype, name,) + options)
  _tkinter.TclError: couldn't recognize data in image file "/Users/Zhou/Project/Tkinter-Designer/gui/assets/TextBox_Bg.png"
  ```

**Comment by ParthJadhav** [comment]
Can u try using a different image ?

**Comment by rdbende** [comment]
Tcl/Tk 8.5 doesn't support png images

**Comment by ParthJadhav** [comment]
I don't think that's the issue @rdbende , TkinterDesigner itself uses Png files

**Comment by rdbende** [comment]
@ParthJadhav Based on the error message he tries to run TkinterDesigner itself.

**Comment by LucaJaich** [comment]
Same issue here.

**Comment by Rakitic07** [comment]
I switched to a more recent version of Python, version `3.12.5`

Additionally, I had to install `Tcl/Tk` using Homebrew:
```
brew install tcl-tk
```
