### ISSUE TITLE
get_color "list index out of range"

### ISSUE THREAD

**Issue by somenzz** [ParthJadhav/Tkinter-Designer#29]
(py38env) ➜  Tkinter-Designer git:(master) git pull
Already up to date.
(py38env) ➜  Tkinter-Designer git:(master) python tkinter_designer.py
2021-06-16 18:31:55.124 Python[80078:7127628] Warning: Expected min height of view: (<NSButton: 0x7fe6fdf1ecd0>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2021-06-16 18:31:56.399 Python[80078:7127628] Warning: Expected min height of view: (<NSButton: 0x7fe6fdf4a3e0>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "tkinter_designer.py", line 29, in btn_clicked
    backend.generate_code(token,URL, output_path)
  File "/Users/aaron/tmp/Tkinter-Designer/backend.py", line 214, in generate_code
    bg = get_color(element)
  File "/Users/aaron/tmp/Tkinter-Designer/backend.py", line 9, in get_color
    el_r = element["fills"][0]["color"]['r'] * 255
IndexError: list index out of range

file:  https://www.figma.com/file/mekIkg9OrUISB7tbvtzbR0/v1?node-id=1%3A416

**Comment by ParthJadhav** [comment]
Sorry for the inconvenience. There was a mistake in the instructions.

- Text should not be named TextArea or anything. Normal text does not need naming.
- TextArea is for multiline input.
- Text Box (Entry) does not support placeholders currently (In Progress).
- Checkbox are not supported currently (In Progress).
- Multi Coloured text in a single line is not supported.
- All the elements except Button and Background should not contain any children. Entry, TextBox should be created using a single rectangles.

I have modified the Figma File to support Tkinter Designer - 
[Have a look.](https://www.figma.com/community/file/986977867287037912/v1-(Fixed))

Here's the generated code - 
[generated_code.zip](https://github.com/ParthJadhav/Tkinter-Designer/files/6663187/generated_code.zip)

Let me know if you need any help.

**Comment by ParthJadhav** [comment]
Hey @somenzz ,
Did that solve the issue ?

**Comment by ParthJadhav** [comment]
Closing due to no response, feel free to reopen.
