### ISSUE TITLE
Python 11 Support

### ISSUE THREAD

**Issue by elyasaf755** [ParthJadhav/Tkinter-Designer#306]
Add support for `Python 11`, as currently `Python 11` developers are not able to install the requirements 'out of the box'.
It can be easily done by updating the `Pillow` version in the `requirements.txt` file from `8.4.0` to `9.4.0`, I tried it myself and no issues so far with the new Pillow version.

**Comment by ParthJadhav** [comment]
Is this fixed in the latest release @elyasaf755 ?

**Comment by robertgro** [comment]
Confirmed. As of now it throws an error message when trying to install via pip:

```"pip install tkdesigner
Collecting tkdesigner
  Using cached tkdesigner-1.0.7-py3-none-any.whl (14 kB)
Collecting Jinja2==3.0.1
  Using cached Jinja2-3.0.1-py3-none-any.whl (133 kB)
Collecting Pillow<9.0.0,>=8.4.0
  Using cached Pillow-8.4.0.tar.gz (49.4 MB)
  Preparing metadata (setup.py) ... done
Collecting requests==2.25.1
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Requirement already satisfied: urllib3<2.0.0,>=1.26.6 in c:\temp\pyProject\lib\site-packages (from tkdesigner) (1.26.14)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.2-cp311-cp311-win_amd64.whl (16 kB)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Installing collected packages: Pillow, MarkupSafe, idna, chardet, certifi, requests, Jinja2, tkdesigner
  DEPRECATION: Pillow is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for Pillow ... error
  error: subprocess-exited-with-error

  × Running setup.py install for Pillow did not run successfully.
  │ exit code: 1
  ╰─> [192 lines of output]
      running install
      C:\Temp\pyProject\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\BdfFontFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\BlpImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\BmpImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ContainerIO.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\CurImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\DcxImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\DdsImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\EpsImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ExifTags.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\features.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\FitsStubImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\FliImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\FontFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\FpxImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\FtexImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\GbrImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\GdImageFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\GifImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\GimpGradientFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\GimpPaletteFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\GribStubImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\Hdf5StubImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\IcnsImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\IcoImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\Image.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageChops.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageCms.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageColor.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageDraw.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageDraw2.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageEnhance.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageFilter.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageFont.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageGrab.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageMath.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageMode.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageMorph.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageOps.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImagePalette.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImagePath.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageQt.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageSequence.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageShow.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageStat.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageTk.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageTransform.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageWin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImtImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\IptcImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\JpegImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\JpegPresets.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\McIdasImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\MicImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\MpegImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\MpoImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\MspImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PaletteFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PalmImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PcdImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PcfFontFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PcxImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PdfImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PdfParser.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PixarImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PngImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PpmImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PsdImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PSDraw.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PyAccess.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\SgiImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\SpiderImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\SunImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\TarIO.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\TgaImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\TiffImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\TiffTags.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\WalImageFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\WebPImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\WmfImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\XbmImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\XpmImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\_binary.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\_tkinter_finder.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\_util.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\_version.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\__init__.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\__main__.py -> build\lib.win-amd64-cpython-311\PIL
      running egg_info
      writing src\Pillow.egg-info\PKG-INFO
      writing dependency_links to src\Pillow.egg-info\dependency_links.txt
      writing top-level names to src\Pillow.egg-info\top_level.txt
      reading manifest file 'src\Pillow.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.clang-format'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.ci'
      adding license file 'LICENSE'
      writing manifest file 'src\Pillow.egg-info\SOURCES.txt'
      running build_ext


      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html

      Traceback (most recent call last):
        File "C:\Users\user\AppData\Local\Temp\pip-install-yg4iq5em\pillow_dc7ac87f6ea649dc9dcd345050750da5\setup.py", line 978, in <module>
          setup(
        File "C:\Temp\pyProject\Lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Temp\pyProject\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Temp\pyProject\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Temp\pyProject\Lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "C:\Temp\pyProject\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Temp\pyProject\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Temp\pyProject\Lib\site-packages\setuptools\command\install.py", line 68, in run
          return orig.install.run(self)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Temp\pyProject\Lib\site-packages\setuptools\_distutils\command\install.py", line 698, in run
          self.run_command('build')
        File "C:\Temp\pyProject\Lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Temp\pyProject\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Temp\pyProject\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Temp\pyProject\Lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "C:\Temp\pyProject\Lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Temp\pyProject\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Temp\pyProject\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Temp\pyProject\Lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "C:\Temp\pyProject\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
          self.build_extensions()
        File "C:\Users\user\AppData\Local\Temp\pip-install-yg4iq5em\pillow_dc7ac87f6ea649dc9dcd345050750da5\setup.py", line 790, in build_extensions
          raise RequiredDependencyException(f)
      RequiredDependencyException: zlib

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\user\AppData\Local\Temp\pip-install-yg4iq5em\pillow_dc7ac87f6ea649dc9dcd345050750da5\setup.py", line 1037, in <module>
          raise RequiredDependencyException(msg)
      RequiredDependencyException:

      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html


      C:\Users\user\AppData\Local\Temp\pip-install-yg4iq5em\pillow_dc7ac87f6ea649dc9dcd345050750da5\setup.py:46: RuntimeWarning: Pillow 8.4.0 does not support Python 3.11 and does not provide prebuilt Windows binaries. We do not recommend building from source on Windows.
        lambda: warnings.warn(
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> Pillow

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip"```

**Comment by natsukashiixo** [comment]
If you install by cloning the repo, it uses pillow 9.4.0 and works on python 3.11. However the pip doesn't seem to be updated for 3.11 support yet
