### ISSUE TITLE
Report bug: Frame not found in figma file or is empty.

### ISSUE THREAD

**Issue by Sxri** [ParthJadhav/Tkinter-Designer#341]
- I already double checked the URL, I'm selecting the frame before copying the URL, all elements are named correctly, nothing is hidden, Token is valid, everything.. But every single time I try and use it, it gives me a whole long error with the last line being "Frame not found in figma file or is empty". I've been trying for two days. Please help me someone!
- Windows 10
- Expected Behavior: Successfully create all elements:

It makes one element then fails. Here is the full error I get: 

Creating Element { name: image, type: rectangle }
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\lurk\Tkinter-Designer\tkdesigner\designer.py", line 21, in to_code
    frame = Frame(f, self.figma_file, self.output_path, self.frameCounter)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lurk\Tkinter-Designer\tkdesigner\figma\frame.py", line 29, in __init__
    self.elements = [
                    ^
  File "C:\Users\lurk\Tkinter-Designer\tkdesigner\figma\frame.py", line 30, in <listcomp>
    self.create_element(child)
  File "C:\Users\lurk\Tkinter-Designer\tkdesigner\figma\frame.py", line 78, in create_element
    download_image(image_url, image_path)
  File "C:\Users\lurk\Tkinter-Designer\tkdesigner\utils.py", line 20, in download_image
    response = requests.get(url)
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\lurk\venv\Lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lurk\venv\Lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\liamb\venv\Lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lurk\venv\Lib\site-packages\requests\sessions.py", line 456, in prepare_request
    p.prepare(
  File "C:\Users\lurk\venv\Lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "C:\Users\lurk\venv\Lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lurk\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\lurk\Tkinter-Designer\gui\gui.py", line 72, in btn_clicked
    designer.design()
  File "C:\Users\lurk\Tkinter-Designer\tkdesigner\designer.py", line 32, in design
    code = self.to_code()
           ^^^^^^^^^^^^^^
  File "C:\Users\lurk\Tkinter-Designer\tkdesigner\designer.py", line 23, in to_code
    raise Exception("Frame not found in figma file or is empty")
Exception: Frame not found in figma file or is empty

**Comment by aellas** [comment]
You need to add a frame to your figma file 
https://help.figma.com/hc/en-us/articles/360039832054-Frames-and-Groups

Example:
<img width="242" alt="image" src="https://github.com/ParthJadhav/Tkinter-Designer/assets/5349544/1c3061ad-aa7c-4f56-9d6e-564305bd8a75">

**Comment by lutfipati96** [comment]
is there a solution to this? I have followed the rules. but the problem is the same.

**Comment by vincentperezzz** [comment]
Creating Element { name: rectangle, type: rectangle }
Creating Element { name: this is a test, type: text }
Creating Element { name: button, type: group }
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Vincent Perez\Desktop\Tkinter-Designer-master\tkdesigner\designer.py", line 21, in to_code
    frame = Frame(f, self.figma_file, self.output_path, self.frameCounter) 
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "C:\Users\Vincent Perez\Desktop\Tkinter-Designer-master\tkdesigner\figma\frame.py", line 29, in __init__
    self.elements = [
                    ^
  File "C:\Users\Vincent Perez\Desktop\Tkinter-Designer-master\tkdesigner\figma\frame.py", line 30, in <listcomp>
    self.create_element(child)
  File "C:\Users\Vincent Perez\Desktop\Tkinter-Designer-master\tkdesigner\figma\frame.py", line 51, in create_element
    download_image(image_url, image_path)
  File "C:\Users\Vincent Perez\Desktop\Tkinter-Designer-master\tkdesigner\utils.py", line 23, in download_image
    im = im.resize((im.size[0] // 2, im.size[1] // 2), Image.ANTIALIAS)    
                                                       ^^^^^^^^^^^^^^^     
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

During handling of the above exception, another exception occurred:        

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Vincent Perez\Desktop\Tkinter-Designer-master\gui\gui.py", line 72, in btn_clicked
    designer.design()
  File "C:\Users\Vincent Perez\Desktop\Tkinter-Designer-master\tkdesigner\designer.py", line 32, in design
    code = self.to_code()
           ^^^^^^^^^^^^^^
  File "C:\Users\Vincent Perez\Desktop\Tkinter-Designer-master\tkdesigner\designer.py", line 23, in to_code
    raise Exception("Frame not found in figma file or is empty")
Exception: Frame not found in figma file or is empty

- I do get the same issue, I already double checked if my frames are correct and the names of my elements but still do get the same error. I did even created a new figma file and made just a simple program that just displays a button and a text still do get the same error.

**Comment by barandenizdogan** [comment]
Read the Install Instructions carefully. You should do following steps.
**1- pip install tkdesigner**
Thats gonna fix all the problems. Clonnig repo and installing requirements not enough.
