### ISSUE TITLE
Pillow Error Help

### ISSUE THREAD

**Issue by Uygar1234** [ParthJadhav/Tkinter-Designer#366]
How to Fix ?

pip install tkdesigner
Collecting tkdesignerNote: you may need to restart the kernel to use updated packages.

  Downloading tkdesigner-1.0.7-py3-none-any.whl (14 kB)
Collecting Jinja2==3.0.1 (from tkdesigner)
  Downloading Jinja2-3.0.1-py3-none-any.whl (133 kB)
     ---------------------------------------- 0.0/133.7 kB ? eta -:--:--
     -------- ------------------------------ 30.7/133.7 kB 1.3 MB/s eta 0:00:01
     -------------------------------- ----- 112.6/133.7 kB 1.6 MB/s eta 0:00:01
     -------------------------------------- 133.7/133.7 kB 1.3 MB/s eta 0:00:00
Collecting Pillow<9.0.0,>=8.4.0 (from tkdesigner)
  Downloading Pillow-8.4.0.tar.gz (49.4 MB)
     ---------------------------------------- 0.0/49.4 MB ? eta -:--:--
     ---------------------------------------- 0.1/49.4 MB 6.8 MB/s eta 0:00:08
     ---------------------------------------- 0.2/49.4 MB 3.8 MB/s eta 0:00:13
     ---------------------------------------- 0.4/49.4 MB 3.1 MB/s eta 0:00:16
     ---------------------------------------- 0.5/49.4 MB 3.5 MB/s eta 0:00:14
      --------------------------------------- 1.0/49.4 MB 5.0 MB/s eta 0:00:10
     - -------------------------------------- 1.6/49.4 MB 6.7 MB/s eta 0:00:08
     - -------------------------------------- 2.4/49.4 MB 8.5 MB/s eta 0:00:06
     -- ------------------------------------- 3.5/49.4 MB 10.6 MB/s eta 0:00:05
     ---- ----------------------------------- 5.3/49.4 MB 14.7 MB/s eta 0:00:03
     ---- ----------------------------------- 5.6/49.4 MB 14.8 MB/s eta 0:00:03
     ----- ---------------------------------- 7.1/49.4 MB 15.6 MB/s eta 0:00:03
     ------- -------------------------------- 9.5/49.4 MB 18.4 MB/s eta 0:00:03
     --------- ----------------------------- 11.8/49.4 MB 36.4 MB/s eta 0:00:02
     --------- ----------------------------- 11.8/49.4 MB 29.8 MB/s eta 0:00:02
     ----------- --------------------------- 15.0/49.4 MB 38.5 MB/s eta 0:00:01
     ------------- ------------------------- 16.6/49.4 MB 50.4 MB/s eta 0:00:01
     ------------- ------------------------- 17.5/49.4 MB 43.5 MB/s eta 0:00:01
     -------------- ------------------------ 19.0/49.4 MB 43.7 MB/s eta 0:00:01
     --------------- ----------------------- 19.4/49.4 MB 38.6 MB/s eta 0:00:01
     ---------------- ---------------------- 20.9/49.4 MB 36.4 MB/s eta 0:00:01
     ----------------- --------------------- 22.3/49.4 MB 38.5 MB/s eta 0:00:01
     ------------------ -------------------- 23.0/49.4 MB 36.3 MB/s eta 0:00:01
     ------------------ -------------------- 23.9/49.4 MB 32.8 MB/s eta 0:00:01
     ------------------- ------------------- 24.6/49.4 MB 27.3 MB/s eta 0:00:01
     --------------------- ----------------- 26.6/49.4 MB 27.3 MB/s eta 0:00:01
     --------------------- ----------------- 27.7/49.4 MB 27.3 MB/s eta 0:00:01
     ---------------------- ---------------- 28.8/49.4 MB 27.3 MB/s eta 0:00:01
     ----------------------- --------------- 29.4/49.4 MB 24.3 MB/s eta 0:00:01
     ----------------------- --------------- 30.2/49.4 MB 27.3 MB/s eta 0:00:01
     ------------------------ -------------- 31.0/49.4 MB 22.5 MB/s eta 0:00:01
     ------------------------- ------------- 31.7/49.4 MB 23.4 MB/s eta 0:00:01
     ------------------------- ------------- 32.8/49.4 MB 22.6 MB/s eta 0:00:01
     -------------------------- ------------ 33.6/49.4 MB 22.6 MB/s eta 0:00:01
     --------------------------- ----------- 34.7/49.4 MB 24.2 MB/s eta 0:00:01
     ---------------------------- ---------- 35.6/49.4 MB 23.4 MB/s eta 0:00:01
     ---------------------------- ---------- 36.4/49.4 MB 21.8 MB/s eta 0:00:01
     ----------------------------- --------- 37.1/49.4 MB 22.5 MB/s eta 0:00:01
     ------------------------------ -------- 38.5/49.4 MB 22.6 MB/s eta 0:00:01
     ------------------------------ -------- 39.2/49.4 MB 22.6 MB/s eta 0:00:01
     ------------------------------- ------- 40.3/49.4 MB 21.8 MB/s eta 0:00:01
     -------------------------------- ------ 41.2/49.4 MB 22.6 MB/s eta 0:00:01
     --------------------------------- ----- 42.4/49.4 MB 23.4 MB/s eta 0:00:01
     ---------------------------------- ---- 43.4/49.4 MB 23.4 MB/s eta 0:00:01
     ----------------------------------- --- 44.4/49.4 MB 23.4 MB/s eta 0:00:01
     ----------------------------------- --- 45.5/49.4 MB 24.2 MB/s eta 0:00:01
     ------------------------------------ -- 46.3/49.4 MB 23.4 MB/s eta 0:00:01
     ------------------------------------- - 47.4/49.4 MB 24.2 MB/s eta 0:00:01
     --------------------------------------  48.4/49.4 MB 22.5 MB/s eta 0:00:01
     --------------------------------------  49.4/49.4 MB 24.2 MB/s eta 0:00:01
     --------------------------------------  49.4/49.4 MB 24.2 MB/s eta 0:00:01
     --------------------------------------- 49.4/49.4 MB 20.4 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting requests==2.25.1 (from tkdesigner)
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     ---------------------------------------- 61.2/61.2 kB ? eta 0:00:00
Requirement already satisfied: urllib3<2.0.0,>=1.26.6 in c:\users\w10\anaconda3\lib\site-packages (from tkdesigner) (1.26.16)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\w10\anaconda3\lib\site-packages (from Jinja2==3.0.1->tkdesigner) (2.1.1)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\w10\anaconda3\lib\site-packages (from requests==2.25.1->tkdesigner) (4.0.0)
Collecting idna<3,>=2.5 (from requests==2.25.1->tkdesigner)
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     ---------------------------------------- 0.0/58.8 kB ? eta -:--:--
     ---------------------------------------- 58.8/58.8 kB 3.0 MB/s eta 0:00:00
Requirement already satisfied: certifi>=2017.4.17 in c:\users\w10\anaconda3\lib\site-packages (from requests==2.25.1->tkdesigner) (2023.5.7)
Building wheels for collected packages: Pillow
  Building wheel for Pillow (setup.py): started
  Building wheel for Pillow (setup.py): finished with status 'error'
  Running setup.py clean for Pillow
Failed to build Pillow
  error: subprocess-exited-with-error
  
  python setup.py bdist_wheel did not run successfully.
  exit code: 1
  
  [187 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-311
  creating build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\BdfFontFile.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\BlpImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\BmpImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\ContainerIO.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\CurImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\DcxImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\DdsImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\EpsImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\ExifTags.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\features.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\FitsStubImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\FliImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\FontFile.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\FpxImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\FtexImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\GbrImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\GdImageFile.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\GifImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\GimpGradientFile.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\GimpPaletteFile.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\GribStubImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\Hdf5StubImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\IcnsImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\IcoImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\Image.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\ImageChops.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\ImageCms.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\ImageColor.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\ImageDraw.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\ImageDraw2.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\ImageEnhance.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\ImageFile.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\ImageFilter.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\ImageFont.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\ImageGrab.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\ImageMath.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\ImageMode.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\ImageMorph.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\ImageOps.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\ImagePalette.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\ImagePath.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\ImageQt.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\ImageSequence.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\ImageShow.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\ImageStat.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\ImageTk.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\ImageTransform.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\ImageWin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\ImImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\ImtImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\IptcImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\JpegImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\JpegPresets.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\McIdasImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\MicImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\MpegImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\MpoImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\MspImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\PaletteFile.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\PalmImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\PcdImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\PcfFontFile.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\PcxImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\PdfImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\PdfParser.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\PixarImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\PngImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\PpmImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\PsdImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\PSDraw.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\PyAccess.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\SgiImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\SpiderImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\SunImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\TarIO.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\TgaImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\TiffImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\TiffTags.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\WalImageFile.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\WebPImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\WmfImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\XbmImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\XpmImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\_binary.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\_tkinter_finder.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\_util.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\_version.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\__init__.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\__main__.py -> build\lib.win-amd64-cpython-311\PIL
  running egg_info
  writing src\Pillow.egg-info\PKG-INFO
  writing dependency_links to src\Pillow.egg-info\dependency_links.txt
  writing top-level names to src\Pillow.egg-info\top_level.txt
  reading manifest file 'src\Pillow.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.c'
  warning: no files found matching '*.h'
  warning: no files found matching '*.sh'
  warning: no previously-included files found matching '.appveyor.yml'
  warning: no previously-included files found matching '.clang-format'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.readthedocs.yml'
  warning: no previously-included files found matching 'codecov.yml'
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  no previously-included directories found matching '.ci'
  adding license file 'LICENSE'
  writing manifest file 'src\Pillow.egg-info\SOURCES.txt'
  running build_ext
  
  
  The headers or library files could not be found for zlib,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  Traceback (most recent call last):
    File "C:\Users\W10\AppData\Local\Temp\pip-install-a_lope_7\pillow_399430580a3047ddb13575f51c4230d5\setup.py", line 978, in <module>
      setup(
    File "C:\Users\W10\anaconda3\Lib\site-packages\setuptools\__init__.py", line 107, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\W10\anaconda3\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "C:\Users\W10\anaconda3\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
      dist.run_commands()
    File "C:\Users\W10\anaconda3\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "C:\Users\W10\anaconda3\Lib\site-packages\setuptools\dist.py", line 1244, in run_command
      super().run_command(command)
    File "C:\Users\W10\anaconda3\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\W10\anaconda3\Lib\site-packages\wheel\bdist_wheel.py", line 325, in run
      self.run_command("build")
    File "C:\Users\W10\anaconda3\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "C:\Users\W10\anaconda3\Lib\site-packages\setuptools\dist.py", line 1244, in run_command
      super().run_command(command)
    File "C:\Users\W10\anaconda3\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\W10\anaconda3\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
      self.run_command(cmd_name)
    File "C:\Users\W10\anaconda3\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "C:\Users\W10\anaconda3\Lib\site-packages\setuptools\dist.py", line 1244, in run_command
      super().run_command(command)
    File "C:\Users\W10\anaconda3\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\W10\anaconda3\Lib\site-packages\setuptools\command\build_ext.py", line 84, in run
      _build_ext.run(self)
    File "C:\Users\W10\anaconda3\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
      self.build_extensions()
    File "C:\Users\W10\AppData\Local\Temp\pip-install-a_lope_7\pillow_399430580a3047ddb13575f51c4230d5\setup.py", line 790, in build_extensions
      raise RequiredDependencyException(f)
  RequiredDependencyException: zlib
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\W10\AppData\Local\Temp\pip-install-a_lope_7\pillow_399430580a3047ddb13575f51c4230d5\setup.py", line 1037, in <module>
      raise RequiredDependencyException(msg)
  RequiredDependencyException:
  
  The headers or library files could not be found for zlib,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  
  C:\Users\W10\AppData\Local\Temp\pip-install-a_lope_7\pillow_399430580a3047ddb13575f51c4230d5\setup.py:46: RuntimeWarning: Pillow 8.4.0 does not support Python 3.11 and does not provide prebuilt Windows binaries. We do not recommend building from source on Windows.
    lambda: warnings.warn(
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Pillow
ERROR: Could not build wheels for Pillow, which is required to install pyproject.toml-based projects

This version of python seems to be incorrectly compiled
(internal generated filenames are not absolute).
This may make the debugger miss breakpoints.
Related bug: http://bugs.python.org/issue1666807

**Comment by barandenizdogan** [comment]
Try to update wheel with 
**python -m pip install -U wheel setuptools**

**Comment by x0bi3** [comment]
Hi, I was in the middle of writing a post bringing yet another problem to the table... Somehow, I think I found the fix.

Enter **pip install Pillow=10.1.0** to download the latest one manually. It seems like the requirements.txt sticks to the 9.4 version, and downloading the outdated version of Pillow isn't allowing it to identify zlib properly.

Hope it helps, good luck!

**Comment by WexeI** [comment]
Maybe you mean **pip install tkdesigner Pillow==10.1.0** ?
