### ISSUE TITLE
 Exception: Frame not found in figma file or is empty

### ISSUE THREAD

**Issue by aglamazlarefe** [ParthJadhav/Tkinter-Designer#367]
Creating Element { name: button, type: group }
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Efe Ağlamazlar\Desktop\sp proje\Tkinter-Designer-master\tkdesigner\designer.py", line 21, in to_code
    frame = Frame(f, self.figma_file, self.output_path, self.frameCounter)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Efe Ağlamazlar\Desktop\sp proje\Tkinter-Designer-master\tkdesigner\figma\frame.py", line 30, in __init__
    self.create_element(child)
  File "C:\Users\Efe Ağlamazlar\Desktop\sp proje\Tkinter-Designer-master\tkdesigner\figma\frame.py", line 51, in create_element
    download_image(image_url, image_path)
  File "C:\Users\Efe Ağlamazlar\Desktop\sp proje\Tkinter-Designer-master\tkdesigner\utils.py", line 23, in download_image
    im = im.resize((im.size[0] // 2, im.size[1] // 2), Image.ANTIALIAS)
                                                       ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Efe Ağlamazlar\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Efe Ağlamazlar\Desktop\sp proje\Tkinter-Designer-master\gui\gui.py", line 72, in btn_clicked
    designer.design()
  File "C:\Users\Efe Ağlamazlar\Desktop\sp proje\Tkinter-Designer-master\tkdesigner\designer.py", line 32, in design
    code = self.to_code()
           ^^^^^^^^^^^^^^
  File "C:\Users\Efe Ağlamazlar\Desktop\sp proje\Tkinter-Designer-master\tkdesigner\designer.py", line 23, in to_code
    raise Exception("Frame not found in figma file or is empty")
Exception: Frame not found in figma file or is empty

but my figma design already have a frames please help me 
![Ekran Alıntısı](https://github.com/ParthJadhav/Tkinter-Designer/assets/111381104/d95890b3-65dc-4bb2-acdc-ba02bce46fbb)

**Comment by matheeshapathirana** [comment]
I got the same problem and fixed it by using python 3.10 venv

**Comment by huzaifa0301** [comment]
can you help me also @matheeshapathirana

**Comment by aglamazlarefe** [comment]
I solved issue. I changed my pc where am ı running file and it worked fine. I recommend you to change pc or create venv.

**Comment by barandenizdogan** [comment]
Changing Pc or env is not the solution. Read the Install Instructions carefully. You should do following steps.
**1- pip install tkdesigner**
Thats gonna fix all the problems. Clonnig repo and installing requirements not enough.
