### ISSUE TITLE
ERROR : Frame not found (BUT FRAME IS THERE)

### ISSUE THREAD

**Issue by Euclid737** [ParthJadhav/Tkinter-Designer#377]
I have created a Design file in Figma, following the steps of the Element Guide as described in https://github.com/ParthJadhav/Tkinter-Designer/blob/master/docs/instructions.md
The created page (File URL) is https://www.figma.com/file/dL344FdpJakjdUg4kEHz6X/iMagine?type=design&node-id=0%3A1&mode=design&t=OpdSedRuJcmGgr19-1

I give this and my Token ID in 'gui.py' but it gives the error : Frame not found in figma file or is empty 

Here is the full error:

PS D:\Tkinter-Designer-master> & "D:/Users/Computer Hub/AppData/Local/Programs/Python/Python312/python.exe" d:/Tkinter-Designer-master/gui/gui.py
Creating Element { name: button, type: rectangle }
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Tkinter-Designer-master\tkdesigner\designer.py", line 21, in to_code
    frame = Frame(f, self.figma_file, self.output_path, self.frameCounter)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Tkinter-Designer-master\tkdesigner\figma\frame.py", line 30, in __init__
    self.create_element(child)
  File "D:\Tkinter-Designer-master\tkdesigner\figma\frame.py", line 51, in create_element
    download_image(image_url, image_path)
  File "D:\Tkinter-Designer-master\tkdesigner\utils.py", line 23, in download_image
    im = im.resize((im.size[0] // 2, im.size[1] // 2), Image.ANTIALIAS)
                                                       ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\Computer Hub\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "d:\Tkinter-Designer-master\gui\gui.py", line 72, in btn_clicked
    designer.design()
  File "D:\Tkinter-Designer-master\tkdesigner\designer.py", line 32, in design
    code = self.to_code()
           ^^^^^^^^^^^^^^
  File "D:\Tkinter-Designer-master\tkdesigner\designer.py", line 23, in to_code
    raise Exception("Frame not found in figma file or is empty")
Exception: Frame not found in figma file or is empty

Please help me.

**Comment by adityax4** [comment]
I had the same issue, but i resolved the issue.
This error is occurring because one module in pillow package is deprecated.
So if you have the latest python 3.12.1, you'll have to install latest pillow package version and use that latest module.

**Comment by seavice** [comment]
Hi mate! I still experience this error. Could please tip what could be wrong here?

`frame = Frame(f, self.figma_file, self.output_path, self.frameCounter)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

Python 3.12.1
pillow 10.2.0 - latest at the moment

**Comment by orcnet** [comment]
I am having the same issue and only downloaded yesterday 12/3/24.
I have tried to update Pillow but it has stated it is up to date.
please help

**Comment by ShevamV** [comment]
I am Having the Same Error
```raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?

During handling of the above exception, another exception occurred:
...
raise Exception("Frame not found in figma file or is empty")
Exception: Frame not found in figma file or is empty
```
like this, Please tell me if there's any solutions

**Comment by EVINJSUBIN** [comment]
same here

**Comment by Sudo-modedd** [comment]
Same, pillow update not fix this.
