### ISSUE TITLE
Help i can't use TKINTER DESGINER PLEASE HELP

### ISSUE THREAD

**Issue by apm-99** [ParthJadhav/Tkinter-Designer#418]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\agusp\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "c:\Users\agusp\projects\Tkinter-Designer-master\gui\gui.py", line 72, in btn_clicked
    designer.design()
  File "C:\Users\agusp\projects\Tkinter-Designer-master\tkdesigner\designer.py", line 32, in design
    code = self.to_code()
           ^^^^^^^^^^^^^^
  File "C:\Users\agusp\projects\Tkinter-Designer-master\tkdesigner\designer.py", line 19, in to_code
    for f in self.file_data["document"]["children"][0]["children"]:
             ~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'document'

**Comment by 9xadx** [comment]
same problem here

**Comment by renderos1-1** [comment]
Same.

**Comment by suryadevelope** [comment]
same issue

**Comment by ThePerfectDesigner** [comment]
I also ran into some issue and could not get them fixed
I tried this new tool, works like charm
https://github.com/nucleonautomation/Gluonix-Designer

**Comment by renderos1-1** [comment]
I forgot to come back here, but I managed to fix it. At least in my case, the issue was that that Figma Token was expired, because I think that by default they expire after 30 days. So it could be that your token is either expired or wrong. Try generating a new one and that should fix the issue.
