### ISSUE TITLE
Figma URL

### ISSUE THREAD

**Issue by softwarecha** [ParthJadhav/Tkinter-Designer#421]
It is always saying a invalid URL even I just paste a URL from my figma file

**Comment by nannerpusser** [comment]
Same issue here, was just questioning my sanity and dissecting the `cli.py` from the library installation dir itself to make sure it wasn't me. The problem seems to be the regex here:

` match = re.search(r'https://www.figma.com/file/([0-9A-Za-z]+)', args.file_url)`

Not a single Share link from anywhere within Figma's web app includes a `/file/` directory in the URL path. I even tried sharing the whole Team and tried Dev Mode, republishing, moved the file, left it Untitled and outside my Project folder, tried the links from Drafts, published to Community then tried the three ways to share it, and several other jackass ideas in order to get a link with `/file/` in the URL. No dice. 

Maybe Figma just changed their link sharing schema? Certainly this project has been working until now, right? If I could get it to at least parse my input and run for debugging I'd link that, but here's the stdout Traceback at least (personal non-essential data removed obviously):

`Traceback (most recent call last):
  File "/tkdesigner", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "<wooptywooowoo>.../tkdesigner/lib/python3.12/site-packages/tkdesigner/cli.py", line 51, in main
    raise ValueError("Invalid file URL.")
ValueError: Invalid file URL.`
