### ISSUE TITLE
Cant run gui

### ISSUE THREAD

**Issue by VillivnarXD** [ParthJadhav/Tkinter-Designer#423]

**Comment by VillivnarXD** [comment]
I can run it now but this error occurs at the end of making the figma gui

Traceback (most recent call last):
  File "C:\Users\ \AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "c:\Users Downloads\Tkinter-Designer-master\gui\gui.py", line 72, in btn_clicked
    designer.design()
  File "C:\Users\ Downloads\Tkinter-Designer-master\tkdesigner\designer.py", line 32, in design
    code = self.to_code()
  File "C:\Users\ \Downloads\Tkinter-Designer-master\tkdesigner\designer.py", line 23, in to_code
    raise Exception("Frame not found in figma file or is empty")

**Comment by MyroslavMay** [comment]
Frame not found in figma file or is empty!

**Comment by AeonShai** [comment]
> I can run it now but this error occurs at the end of making the figma gui
> 
> Traceback (most recent call last): File "C:\Users\ \AppData\Local\Programs\Python\Python310\lib\tkinter__init__.py", line 1921, in **call** return self.func(*args) File "c:\Users Downloads\Tkinter-Designer-master\gui\gui.py", line 72, in btn_clicked designer.design() File "C:\Users\ Downloads\Tkinter-Designer-master\tkdesigner\designer.py", line 32, in design code = self.to_code() File "C:\Users\ \Downloads\Tkinter-Designer-master\tkdesigner\designer.py", line 23, in to_code raise Exception("Frame not found in figma file or is empty")
> 
> ```
> File "C:\Users\\Downloads\Tkinter-Designer-master\tkdesigner\designer.py", line 21, in to_code
> frame = Frame(f, self.figma_file, self.output_path, self.frameCounter)
> ```
> 
> File "C:\Users\Downloads\Tkinter-Designer-master\tkdesigner\figma\frame.py", line 29, in **init** self.elements = [ File "C:\Users\if\Downloads\Tkinter-Designer-master\tkdesigner\figma\frame.py", line 30, in self.create_element(child) File "C:\Users\f\Downloads\Tkinter-Designer-master\tkdesigner\figma\frame.py", line 93, in create_element download_image(image_url, image_path) File "C:\Users\Kashif\Downloads\Tkinter-Designer-master\tkdesigner\utils.py", line 20, in download_image response = requests.get(url) File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 76, in get return request('get', url, params=params, **kwargs) File "C:\Users\K\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 61, in request return session.request(method=method, url=url, **kwargs) File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 528, in request prep = self.prepare_request(req) File "C:\Users\f\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 456, in prepare_request p.prepare( File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 316, in prepare self.prepare_url(url, params) File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 390, in prepare_url raise MissingSchema(error) requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\Users\f\AppData\Local\Programs\Python\Python310\lib\tkinter__init__.py", line 1921, in **call** return self.func(*args) File "c:\Users\Downloads\Tkinter-Designer-master\gui\gui.py", line 72, in btn_clicked designer.design() File "C:\Users\Downloads\Tkinter-Designer-master\tkdesigner\designer.py", line 32, in design code = self.to_code() File "C:\Users\Downloads\Tkinter-Designer-master\tkdesigner\designer.py", line 23, in to_code raise Exception("Frame not found in figma file or is empty") Exception: Frame not found in figma file or is empty

How did u solve first problem?
