### ISSUE TITLE
Generation not Working

### ISSUE THREAD

**Issue by ilightelectric** [ParthJadhav/Tkinter-Designer#431]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Dell\Downloads\Tkinter-Designer-master\Tkinter-Designer-master\tkdesigner\designer.py", line 21, in to_code
    frame = Frame(f, self.figma_file, self.output_path, self.frameCounter)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\Downloads\Tkinter-Designer-master\Tkinter-Designer-master\tkdesigner\figma\frame.py", line 29, in __init__
    self.elements = [
                    ^
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\tkinter\__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\Downloads\Tkinter-Designer-master\Tkinter-Designer-master\gui\gui.py", line 72, in btn_clicked
    designer.design()
  File "C:\Users\Dell\Downloads\Tkinter-Designer-master\Tkinter-Designer-master\tkdesigner\designer.py", line 32, in design
    code = self.to_code()
           ^^^^^^^^^^^^^^
  File "C:\Users\Dell\Downloads\Tkinter-Designer-master\Tkinter-Designer-master\tkdesigner\designer.py", line 23, in to_code
    raise Exception("Frame not found in figma file or is empty")
Exception: Frame not found in figma file or is empty

I Get this error when i press "Generate"

**Comment by ammar26627** [comment]
Tkinter Designer detects the frame element in figma as a base. You need to first create a frame and then add other elements like buttons, texts in it
