### ISSUE TITLE
    raise Exception("Frame not found in figma file or is empty") Exception: Frame not found in figma file or is empty

### ISSUE THREAD

**Issue by EVINJSUBIN** [ParthJadhav/Tkinter-Designer#436]
Traceback (most recent call last):
  File "/home/youridertech/Tkinter-Designer-1.0.7/Tkinter-Designer-1.0.7/tkdesigner/designer.py", line 21, in to_code
    frame = Frame(f, self.figma_file, self.output_path, self.frameCounter)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/youridertech/Tkinter-Designer-1.0.7/Tkinter-Designer-1.0.7/tkdesigner/figma/frame.py", line 29, in __init__
    self.elements = [
                    ^
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/home/youridertech/Tkinter-Designer-1.0.7/Tkinter-Designer-1.0.7/gui/gui.py", line 72, in btn_clicked
    designer.design()
  File "/home/youridertech/Tkinter-Designer-1.0.7/Tkinter-Designer-1.0.7/tkdesigner/designer.py", line 32, in design
    code = self.to_code()
           ^^^^^^^^^^^^^^
  File "/home/youridertech/Tkinter-Designer-1.0.7/Tkinter-Designer-1.0.7/tkdesigner/designer.py", line 23, in to_code
    raise Exception("Frame not found in figma file or is empty")
Exception: Frame not found in figma file or is empty

**Comment by ammar26627** [comment]
In Figma, you need to make the base as a frame element. I assume you started with a rectangle

**Comment by EVINJSUBIN** [comment]
Yes Bro Thank you
