### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ahmedyousry18** [ParthJadhav/Tkinter-Designer#439]
How to Fix ?
A key error occurs when the elements are named or grouped incorrectly. Before creating an issue, make sure that you have followed the [instructions](https://github.com/ParthJadhav/Tkinter-Designer/blob/master/docs/instructions.md) guide correctly.  

If the issue still persists, create an issue with the following details included.

1. Error Message

PS C:\Users\Ahmed Yousry\Desktop\Tkinter-Designer-master> & "C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python39_64/python.exe" "c:/Users/Ahmed Yousry/Desktop/Tkinter-Designer-master/gui/gui.py"
Traceback (most recent call last):
  File "c:\Users\Ahmed Yousry\Desktop\Tkinter-Designer-master\gui\gui.py", line 13, in <module>
    from tkdesigner.designer import Designer
  File "C:\Users\Ahmed Yousry\Desktop\Tkinter-Designer-master\tkdesigner\designer.py", line 1, in <module>
    import tkdesigner.figma.endpoints as endpoints
  File "C:\Users\Ahmed Yousry\Desktop\Tkinter-Designer-master\tkdesigner\figma\endpoints.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Ahmed Yousry\Desktop\Tkinter-Designer-master\gui\gui.py", line 15, in <module>
    raise RuntimeError("Couldn't add tkdesigner to the PATH.")
RuntimeError: Couldn't add tkdesigner to the PATH.

3. Link to the Figma File

gui/gui.py

**Comment by Kunal-Garg-12** [comment]
Hi @ahmedyousry18 , open cli and run 'pip install requests'
