### ISSUE TITLE
Report bug

### ISSUE THREAD

**Issue by skalwaghe-56** [ParthJadhav/Tkinter-Designer#456]
When I am trying to install the Tkinter-Designer with the command `pip install tkdesigner --verbose`
I am getting the below error:

```
Traceback (most recent call last):
    File "C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
      ~~~~^^
    File "C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-gt3yxibg\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=[])
             ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-gt3yxibg\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
      self.run_setup()
      ~~~~~~~~~~~~~~^^
    File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-gt3yxibg\overlay\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
      super().run_setup(setup_script=setup_script)
      ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-gt3yxibg\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
      exec(code, locals())
      ~~~~^^^^^^^^^^^^^^^^
    File "<string>", line 30, in <module>
    File "<string>", line 26, in get_version
  KeyError: '__version__'
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'C:\Users\Admin\AppData\Local\Programs\Python\Python313\python.exe' 'C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\Admin\AppData\Local\Temp\tmpwrzfcv7h'
  cwd: C:\Users\Admin\AppData\Local\Temp\pip-install-bwhcq6cc\pillow_08d71b8be663412dbdcf619a70a4f713
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I tried with the flag `--verbose` but the same error was seen and I couldn't find anything new.

I have Windows 11 23H2 and have the latest version of pip and python as 24.3.1 and 3.13 respectively.

It should have installed properly as it works for other people. (maybe i dunno)

The error can be reproduced by trying to install the package again.

**Comment by DetroNot74** [comment]
i had the same error with python 3.13  **TRY USING OLDER VERSION** of python.
It works **3.10** but with slight misAlignment in the GUI.
May prefer older-version as when the app was written just to generate your UI.

**Comment by biohazard-luke** [comment]
i changed the python version and it passed this error but i'm gettin another
