### ISSUE TITLE
json Decode Error

### ISSUE THREAD

**Issue by Vinyzuz** [ParthJadhav/Tkinter-Designer#46]
The Error is:
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\\Desktop\coding\!Coding\Tkinter-Designer-master\tkinter_designer.py", line 29, in btn_clicked
    backend.generate_code(token,URL, output_path)
  File "C:\Users\\Desktop\coding\!Coding\Tkinter-Designer-master\backend.py", line 91, in generate_code
    data = response.json()
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Link to Figma FIle:
https://www.figma.com/file/SmMH601IW47DIQ8RsyiMZQ/Untitled?node-id=0%3A1

Btw before this i got this error:

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\\Desktop\coding\!Coding\Tkinter-Designer-master\tkinter_designer.py", line 29, in btn_clicked
    backend.generate_code(token,URL, output_path)
  File "C:\Users\\Desktop\coding\!Coding\Tkinter-Designer-master\backend.py", line 147, in generate_code
    window_elements = fig_window["children"]
KeyError: 'children

**Comment by ParthJadhav** [comment]
Thanks for creating an issue, we are eager to solve it.

**Comment by ParthJadhav** [comment]
Hey @Vinyzuz, The JSON decode error is unexpectedly occurring today. And it goes away after a second time.

And let me see about the second.

**Comment by ParthJadhav** [comment]
Hey @Vinyzuz, The keyError children is due to there are no valid elements inside the frame. Add some text and it should work.

Also use the latest version.

**Comment by ParthJadhav** [comment]
Also I recorded the response and the JSON decoder error is caused because of The Figma server. 
When this error occurs the status code is - 504 Gateway Timeout.

It means that there's no problem with Tkinter Designer. It would go away soon. Until then we just have option of retrying.

**Comment by Vinyzuz** [comment]
ok thanks

**Comment by ParthJadhav** [comment]
Hey @Vinyzuz , the json decode error
Must have solved now.

**Comment by JawadPy** [comment]
Same error now, even after updating tkd @ParthJadhav
