### ISSUE TITLE
Error reporting, exception in Tkinter.

### ISSUE THREAD

**Issue by MarianoTupa** [ParthJadhav/Tkinter-Designer#52]
### Discussed in https://github.com/ParthJadhav/Tkinter-Designer/discussions/51

<div type='discussions-op-text'>

<sup>Originally posted by **MarianoTupa** June 21, 2021</sup>
Hello, I am trying to run this app on my machine. This error is running me.

```
'color'
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/tupadev/miniconda3/envs/tkinter-figma/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "tkinter_designer.py", line 29, in btn_clicked
    backend.generate_code(token,URL, output_path)
  File "/mnt/c/Users/tupa/Workspace/Tkinter-Designer/backend.py", line 147, in generate_code
    window_elements = fig_window["children"]
KeyError: 'children'
```
</div>

**Comment by ParthJadhav** [comment]
Thanks for creating an issue, we are eager to solve it.

**Comment by ParthJadhav** [comment]
Hey @MarianoTupa please share link to your Figma file.
