### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by RiseToDev751** [ParthJadhav/Tkinter-Designer#54]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\aga53\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1885, in __call__
    return self.func(*args)
  File "C:\Users\aga53\Desktop\Tkinter-Designer-master\tkinter_designer.py", line 29, in btn_clicked
    backend.generate_code(token,URL, output_path)
  File "C:\Users\aga53\Desktop\Tkinter-Designer-master\backend.py", line 147, in generate_code
    window_elements = fig_window["children"]
KeyError: 'children'

https://www.figma.com/file/oAIOBRAAl45enA7k1CWy4k/Untitled?node-id=1%3A18

**Comment by ParthJadhav** [comment]
Thanks for creating an issue, we are eager to solve it.

**Comment by ParthJadhav** [comment]
Hey @RiseToDev751 , The element named Rectangle 1 which you have used as a container or window for other elements is not right. You should use frame as a container. Rest all is correct.

https://www.figma.com/file/fIWLWPhTdkcqM9Qi5vDkte/Fixed?node-id=0%3A1

I have fixed the problem in the above link.

**Comment by RiseToDev751** [comment]
Thanks you @ParthJadhav
