### ISSUE TITLE
Using a Figma Design file without a Frame doesn't notify the user of failure.

### ISSUE THREAD

**Issue by piccoloser** [ParthJadhav/Tkinter-Designer#6]
If you enter a Figma Design URL for a file that doesn't have a Frame, the program will output the following to the terminal:
```python
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\tkinter\__init__.py", line 1884, in __call__
    return self.func(*args)
  File "C:\LocalDev\Forks\Tkinter-Designer\tkinter_designer.py", line 21, in btnClicked
    backend.generate_code(token,URL, path_to_save)
  File "C:\LocalDev\Forks\Tkinter-Designer\backend.py", line 69, in generate_code
    fig_window = data["document"]["children"][0]['children'][0]
IndexError: list index out of range
```

There should be some kind of pop-up that alerts the user to the issue at hand (ex. "Your Figma Design file does not contain a Frame")

**Comment by ParthJadhav** [comment]
Yes, I need to fix this...

**Comment by ParthJadhav** [comment]
Fixed in the latest commit.
