### ISSUE TITLE
File not generated

### ISSUE THREAD

**Issue by nimiology** [ParthJadhav/Tkinter-Designer#90]
Hi!
I can't get the generated code but I get this error  :
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/Users/nima/Desktop/Tkinter-Designer/gui/gui.py", line 73, in btn_clicked
    designer.design()
  File "/Users/nima/Desktop/Tkinter-Designer/tkdesigner/designer.py", line 29, in design
    code = self.to_code()
  File "/Users/nima/Desktop/Tkinter-Designer/tkdesigner/designer.py", line 23, in to_code
    frame = Frame(window_data, self.figma_file, self.output_path)
  File "/Users/nima/Desktop/Tkinter-Designer/tkdesigner/figma/frame.py", line 30, in __init__
    self.elements = [
  File "/Users/nima/Desktop/Tkinter-Designer/tkdesigner/figma/frame.py", line 31, in <listcomp>
    self.create_element(child)
  File "/Users/nima/Desktop/Tkinter-Designer/tkdesigner/figma/frame.py", line 89, in create_element
    return Text(element, self)
  File "/Users/nima/Desktop/Tkinter-Designer/tkdesigner/figma/custom_elements.py", line 44, in __init__
    self.font, self.font_size = self.font_property()
  File "/Users/nima/Desktop/Tkinter-Designer/tkdesigner/figma/custom_elements.py", line 68, in font_property
    font_name = font_name.replace('-', ' ')
AttributeError: 'NoneType' object has no attribute 'replace'


```
This is my Figma link:
https://www.figma.com/file/1PkBD3ubNQIQdRdGjz5EoM/Untitled?node-id=0%3A1

**Comment by nimiology** [comment]
I cant use roboto font :/

**Comment by saur0x** [comment]
I get file not found on this file URL. @nimiology

**Comment by nimiology** [comment]
I fixed that

**Comment by nimiology** [comment]
Try again

**Comment by ParthJadhav** [comment]
Just add a frame. Press F and create a frame for other elements to sit in.

**Comment by nimiology** [comment]
When I use the frame it shows black rectangle

**Comment by saur0x** [comment]
@nimiology https://github.com/ParthJadhav/Tkinter-Designer/blob/master/docs/instructions.md#naming-is-important

**Comment by saur0x** [comment]
One more reason to have a proper element naming scheme.

**Comment by ParthJadhav** [comment]
> @nimiology https://github.com/ParthJadhav/Tkinter-Designer/blob/master/docs/instructions.md#naming-is-important

Yes ! I have fixed it for now. But keep in mind 😃

**Comment by ParthJadhav** [comment]
> One more reason to have a proper element naming scheme.

Yes, We should discuss it further.

**Comment by nimiology** [comment]
It worked
Thanks, guys.
It's awesome!

**Comment by saur0x** [comment]
@nimiology I think the text wrapping isn't working correctly right now. Can you please verify it on https://github.com/saur0x/Tkinter-Designer/tree/text ? I added text wrapping.

**Comment by nimiology** [comment]
What should I verify?

**Comment by saur0x** [comment]
The line that says "Nine noble families..." isn't wrapped in the generated file as it is in the Figma file and the case of that text is also not correct. I added these patches and want someone to verify it before making a PR. @nimiology

**Comment by nimiology** [comment]
I used tkinter-designer on text and main branch but it didn't work correctly!

**Comment by saur0x** [comment]
> I used tkinter-designer on text and main branch either but it didn't work correctly!

Can you be a bit more specific about what didn't work? It would really help with patching these issues.

**Comment by nimiology** [comment]
well the line that says "Nine noble families..." isn't wrapped  in the generated file as it is in the Figma

**Comment by saur0x** [comment]
Can you share a screenshot of the generated window?

**Comment by nimiology** [comment]
![Uploading Untitled.png…]()

**Comment by nimiology** [comment]
![Untitled](https://user-images.githubusercontent.com/73313947/126819133-8b5a710a-a6de-40a4-b9a5-3b20ed2bbaa4.png)

**Comment by saur0x** [comment]
![image](https://user-images.githubusercontent.com/86295845/126852135-59c74c92-13df-47c3-8c49-a682ee1ed6cf.png)
It doesn't look exactly like the Figma file because my system doesn't have the Roboto Slab font installed. It's generated using the `text` branch of my fork.

**Comment by nimiology** [comment]
new Error
```
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
```
link:
https://www.figma.com/file/1PkBD3ubNQIQdRdGjz5EoM/Imdb-page?node-id=0%3A1

**Comment by nimiology** [comment]
full log
```
Creating Element { name: Image, type: RECTANGLE }
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "gui.py", line 73, in btn_clicked
    designer.design()
  File "D:\Programming\Tkinter-Designer\tkdesigner\designer.py", line 29, in design
    code = self.to_code()
  File "D:\Programming\Tkinter-Designer\tkdesigner\designer.py", line 23, in to_code
    frame = Frame(window_data, self.figma_file, self.output_path)
  File "D:\Programming\Tkinter-Designer\tkdesigner\figma\frame.py", line 30, in __init__
    self.elements = [
  File "D:\Programming\Tkinter-Designer\tkdesigner\figma\frame.py", line 31, in <listcomp>
    self.create_element(child)
  File "D:\Programming\Tkinter-Designer\tkdesigner\figma\frame.py", line 81, in create_element
    download_image(image_url, image_path)
  File "D:\Programming\Tkinter-Designer\tkdesigner\utils.py", line 18, in download_image
    response = requests.get(url)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 456, in prepare_request
    p.prepare(
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
Creating Element { name: Image, type: RECTANGLE }
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "gui.py", line 73, in btn_clicked
    designer.design()
  File "D:\Programming\Tkinter-Designer\tkdesigner\designer.py", line 29, in design
    code = self.to_code()
  File "D:\Programming\Tkinter-Designer\tkdesigner\designer.py", line 23, in to_code
    frame = Frame(window_data, self.figma_file, self.output_path)
  File "D:\Programming\Tkinter-Designer\tkdesigner\figma\frame.py", line 30, in __init__
    self.elements = [
  File "D:\Programming\Tkinter-Designer\tkdesigner\figma\frame.py", line 31, in <listcomp>
    self.create_element(child)
  File "D:\Programming\Tkinter-Designer\tkdesigner\figma\frame.py", line 81, in create_element
    download_image(image_url, image_path)
  File "D:\Programming\Tkinter-Designer\tkdesigner\utils.py", line 18, in download_image
    response = requests.get(url)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 456, in prepare_request
    p.prepare(
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
```

**Comment by nimiology** [comment]
new error
```
Creating Element { name: Image, type: RECTANGLE }
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "gui.py", line 73, in btn_clicked
    designer.design()
  File "D:\Programming\Tkinter-Designer\tkdesigner\designer.py", line 29, in design
    code = self.to_code()
  File "D:\Programming\Tkinter-Designer\tkdesigner\designer.py", line 23, in to_code
    frame = Frame(window_data, self.figma_file, self.output_path)
  File "D:\Programming\Tkinter-Designer\tkdesigner\figma\frame.py", line 30, in __init__
    self.elements = [
  File "D:\Programming\Tkinter-Designer\tkdesigner\figma\frame.py", line 31, in <listcomp>
    self.create_element(child)
  File "D:\Programming\Tkinter-Designer\tkdesigner\figma\frame.py", line 81, in create_element
    download_image(image_url, image_path)
  File "D:\Programming\Tkinter-Designer\tkdesigner\utils.py", line 18, in download_image
    response = requests.get(url)
  File "D:\Programming\Tkinter-Designer\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "D:\Programming\Tkinter-Designer\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Programming\Tkinter-Designer\venv\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "D:\Programming\Tkinter-Designer\venv\lib\site-packages\requests\sessions.py", line 456, in prepare_request
    p.prepare(
  File "D:\Programming\Tkinter-Designer\venv\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "D:\Programming\Tkinter-Designer\venv\lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
```

**Comment by saur0x** [comment]
The blob image element is hidden in your Figma file but is named `Image`. So the program tries to download that image but Figma returns no URL for it and the downloading fails, that's why you get that error. You can unhide that element, or rename it to something other than `Image`. @nimiology

**Comment by saur0x** [comment]
I added support for invisible elements, so you won't get that error now.

**Comment by nimiology** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/86295845/126852135-59c74c92-13df-47c3-8c49-a682ee1ed6cf.png)
> It doesn't look exactly like the Figma file because my system doesn't have the Roboto Slab font installed. It's generated using the `text` branch of my fork.

Didn't change for me :/

**Comment by nimiology** [comment]
It's working perfectly.

**Comment by nimiology** [comment]
It was my silly mistake
